"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$cmd_duration\
$line_break\
$jobs\
$character"""

[directory]
read_only = " "
truncation_length = 8

[character]
format = "$symbol "
success_symbol = "[](yellow)"
error_symbol = "[](red)"

